services:
  zookeeper:
    image: zookeeper:latest
    container_name: mapped-zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: mapped-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # External listener port for host machine
      - "29092:29092" # Internal listener port for other containers
    environment:
      KAFKA_ZOOKEEPER_CONNECT: mapped-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mapped-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "29092"]
      interval: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: mapped-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
