name: Mapped-CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.x]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build the project
              run: npm run build --if-present

            - name: Run Lint
              run: npm run lint

            - name: Build the docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/mapped:latest .

            - name: Login to Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Push docker image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/mapped:latest

            - name: Configure SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            

            - name: Login to EC2 and Deploy
              run: |
                ssh  -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} <<EOF
                  cd /home/ubuntu/mapped
                  git pull origin main
                  docker-compose pull
                  docker-compose down
                  docker-compose up --build -d
                EOF

              
      